services:
  backend:
    image: 'backend:latest'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        MARIADB_USER: ${DB_USER}
        MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8080:8080'
    environment:
      DB_URL: jdbc:mariadb://mariadb:3306/mydatabase
      MARIADB_USER: myuser
      MARIADB_PASSWORD: secret
    depends_on:
      - mariadb
  mariadb:
    image: 'mariadb:latest'
    ports:
      - '3306:3306'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    volumes:
      - ./stylish.sql:/docker-entrypoint-initdb.d/stylish.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: mariadb
      MARIADB_PASSWORD: '${MARIADB_PASSWORD}'
    depends_on:
      - mariadb
